"""
utils/constants.py
All static data: districts, crops, soils, translations.
"""

#  Districts 
DISTRICTS = {
    "Dhaka":         (23.8103, 90.4125),
    "Chittagong":    (22.3569, 91.7832),
    "Rajshahi":      (24.3745, 88.6042),
    "Khulna":        (22.8456, 89.5403),
    "Sylhet":        (24.8949, 91.8687),
    "Barisal":       (22.7010, 90.3535),
    "Rangpur":       (25.7439, 89.2752),
    "Mymensingh":    (24.7471, 90.4203),
    "Comilla":       (23.4607, 91.1809),
    "Narayanganj":   (23.6238, 90.4999),
    "Gazipur":       (23.9999, 90.4203),
    "Jessore":       (23.1667, 89.2167),
    "Bogra":         (24.8465, 89.3773),
    "Dinajpur":      (25.6279, 88.6338),
    "Tangail":       (24.2512, 89.9167),
    "Faridpur":      (23.6070, 89.8429),
    "Pabna":         (24.0064, 89.2372),
    "Noakhali":      (22.8696, 91.0996),
    "Brahmanbaria":  (23.9570, 91.1115),
    "Manikganj":     (23.8634, 90.0024),
}

RAIN_MAP = {
    "Sylhet": 2800, "Chittagong": 2500, "Rangpur": 1800, "Dhaka": 1600,
    "Mymensingh": 1900, "Comilla": 1700, "Rajshahi": 1200, "Khulna": 1400,
    "Barisal": 1800, "Bogra": 1400, "Dinajpur": 1500, "Faridpur": 1600,
    "Jessore": 1300, "Tangail": 1700, "Pabna": 1350, "Noakhali": 1900,
    "Brahmanbaria": 1750, "Gazipur": 1650, "Narayanganj": 1600, "Manikganj": 1600,
}

#  Crops 
CROPS = {
    "ধান-বোরো":   {"base": 4.8,  "to": 25, "ro": 1200, "ns": 0.020},
    "ধান-আমন":    {"base": 3.5,  "to": 28, "ro": 1800, "ns": 0.015},
    "ধান-আউশ":    {"base": 2.8,  "to": 30, "ro": 1400, "ns": 0.012},
    "গম":          {"base": 3.2,  "to": 20, "ro": 500,  "ns": 0.022},
    "ভুট্টা":      {"base": 5.0,  "to": 26, "ro": 800,  "ns": 0.025},
    "আলু":         {"base": 22.0, "to": 18, "ro": 500,  "ns": 0.050},
    "পাট":         {"base": 2.5,  "to": 32, "ro": 1500, "ns": 0.010},
    "আখ":          {"base": 65.0, "to": 30, "ro": 1400, "ns": 0.070},
    "সরিষা":       {"base": 1.6,  "to": 18, "ro": 400,  "ns": 0.012},
    "মসুর":        {"base": 1.4,  "to": 20, "ro": 350,  "ns": 0.008},
    "বেগুন":       {"base": 18.0, "to": 25, "ro": 600,  "ns": 0.040},
    "টমেটো":       {"base": 25.0, "to": 24, "ro": 600,  "ns": 0.055},
    "পেঁয়াজ":     {"base": 12.0, "to": 22, "ro": 500,  "ns": 0.030},
    "মরিচ":        {"base": 8.0,  "to": 28, "ro": 700,  "ns": 0.025},
    "সয়াবিন":     {"base": 2.8,  "to": 25, "ro": 700,  "ns": 0.014},
}

#  Soil / irrigation 
SOILS   = ["দোআঁশ (Loamy)", "এঁটেল (Clay)", "বেলে (Sandy)",
           "পলি (Silty)", "বেলে-দোআঁশ (Sandy Loam)", "এঁটেল-দোআঁশ (Clay Loam)"]

SEASONS = ["খরিফ-১", "খরিফ-২", "রবি", "বোরো", "আউশ"]

IRRS    = ["বৃষ্টিনির্ভর", "ভূগর্ভস্থ পানি (STW)", "গভীর নলকূপ (DTW)",
           "ড্রিপ সেচ", "স্প্রিংকলার", "খাল/নদী"]

SM = {
    "দোআঁশ (Loamy)": 1.10, "এঁটেল (Clay)": 0.88, "বেলে (Sandy)": 0.78,
    "পলি (Silty)": 1.05, "বেলে-দোআঁশ (Sandy Loam)": 1.00,
    "এঁটেল-দোআঁশ (Clay Loam)": 1.02,
}

IM = {
    "বৃষ্টিনির্ভর": 0.75, "ভূগর্ভস্থ পানি (STW)": 1.05,
    "গভীর নলকূপ (DTW)": 1.10, "ড্রিপ সেচ": 1.20,
    "স্প্রিংকলার": 1.12, "খাল/নদী": 0.95,
}

#  API 
OWM_API_KEY = "73b5368b5362fd8d3c573da5ed0e9ab0"
CACHE_TTL   = 3600   # seconds

#  Translations 
T = {
    "en": {
        "title": "CropSense AI",
        "subtitle": "Real-time Weather Based Crop Yield Prediction",
        "login_title": "Login to CropSense AI",
        "register_title": "Create New Account",
        "username": "Username", "password": "Password",
        "confirm_password": "Confirm Password",
        "login_btn": "Login", "register_btn": "Register",
        "logout_btn": "Logout",
        "login_tab": "Login", "register_tab": "Register",
        "reg_success": "Account created successfully! You can now login.",
        "reg_exists": "Username already taken. Try another.",
        "reg_user_short": "Username must be at least 3 characters.",
        "reg_pass_short": "Password must be at least 6 characters.",
        "reg_pass_mismatch": "Passwords do not match!",
        "login_success": "Login successful! Welcome",
        "login_error": "Incorrect username or password!",
        "language": "Language",
        "district": "District & Weather", "select_district": "Select District",
        "get_weather": "Get Weather", "fetching": "Fetching weather...",
        "weather_ok": "Success", "weather_err": "Error",
        "crop_field": "Crop & Field", "crop_name": "Crop Name",
        "soil_type": "Soil Type", "season": "Season",
        "irrigation": "Irrigation Method", "field_area": "Field Area (hectare)",
        "weather_section": "Weather", "auto": "(Auto)",
        "temperature": "Temperature (C)", "rainfall": "Annual Rainfall (mm)",
        "humidity": "Humidity (%)", "sunshine": "Sunshine (hours/day)",
        "soil_inputs": "Soil & Fertilizer", "soil_ph": "Soil pH",
        "nitrogen": "Nitrogen/Urea (kg/ha)", "phosphorus": "Phosphorus/TSP (kg/ha)",
        "potassium": "Potassium/MOP (kg/ha)", "pesticide": "Pesticide (kg/ha)",
        "predict_btn": "Predict Yield",
        "current_weather": "Current Weather", "live": "Live", "cache": "Cache",
        "weather_info": "Select a district and click 'Get Weather' — temperature and humidity will be set automatically!",
        "ton_ha": "Ton / Hectare", "predicted": "Predicted Yield",
        "total_ton": "Total Ton", "for_ha": "for {a} hectare",
        "uncertainty": "Uncertainty", "ci": "95% CI [{lo} - {hi}]",
        "vs_avg": "vs Average", "avg": "Avg: {avg} t/ha",
        "great": "Excellent! {dl:.1f}% more yield than average is expected.",
        "good": "Good condition. You will get close to the average yield of {ct}.",
        "warn": "Warning! Yield may be below average. Reconsider soil pH and fertilizer.",
        "tab1": "Analytics", "tab2": "Feature Impact", "tab3": "Data",
        "tab4": "Model Report", "tab5": "My History",
        "dist_chart": "Yield Distribution", "your": "Yours",
        "field_profile": "Field Profile", "season_chart": "Average Yield by Season",
        "top10": "Top 10 Crops", "avg_yield": "Avg Yield (t/ha)",
        "feature_title": "Which factor has the most impact?",
        "feature_rank": "Feature Importance Ranking",
        "sensitivity": "Sensitivity Analysis", "select_feature": "Select feature:",
        "current": "Current", "yield_vs": "Yield vs",
        "data_title": "Data Explorer", "total_records": "Total Records",
        "crop_types": "Crop Types", "avg_yield_lbl": "Avg Yield",
        "x_axis": "X Axis:", "raw_data": "View Raw Data",
        "model_title": "Model Performance Report",
        "test_r2": "Test R2", "test_mae": "Test MAE", "test_rmse": "Test RMSE",
        "cv_r2": "CV R2",
        "no_overfit": "No Overfitting! Train-Test R2 gap = {gap:.4f} (ideal < 0.05)",
        "slight_overfit": "Slight Overfitting. Gap = {gap:.4f}",
        "overfit": "Overfitting detected. Gap = {gap:.4f}",
        "improvements": "Improvements Applied",
        "train_vs_test": "Train vs Test Comparison",
        "actual_vs_pred": "Actual vs Predicted (Test Set)",
        "predictions": "Predictions", "perfect_fit": "Perfect Fit",
        "footer": "CropSense AI - Bangladesh Agriculture - Streamlit + Scikit-learn + OpenWeatherMap",
        "logged_in_as": "Logged in as",
        "history_title": "My Prediction History",
        "no_history": "No predictions saved yet.",
        "hist_crop": "Crop", "hist_district": "District",
        "hist_yield": "Yield (t/ha)", "hist_total": "Total (t)",
        "hist_area": "Area (ha)", "hist_date": "Date",
    },
    "bn": {
        "title": "CropSense AI",
        "subtitle": "রিয়েল-টাইম আবহাওয়া সহ ফসলের ফলন পূর্বাভাস",
        "login_title": "CropSense AI তে লগইন করুন",
        "register_title": "নতুন অ্যাকাউন্ট তৈরি করুন",
        "username": "ব্যবহারকারীর নাম", "password": "পাসওয়ার্ড",
        "confirm_password": "পাসওয়ার্ড নিশ্চিত করুন",
        "login_btn": "লগইন", "register_btn": "রেজিস্ট্রেশন করুন",
        "logout_btn": "লগআউট",
        "login_tab": "লগইন", "register_tab": "নতুন অ্যাকাউন্ট",
        "reg_success": "অ্যাকাউন্ট সফলভাবে তৈরি হয়েছে! এখন লগইন করুন।",
        "reg_exists": "এই নামে অ্যাকাউন্ট আছে। অন্য নাম দিন।",
        "reg_user_short": "ব্যবহারকারীর নাম কমপক্ষে ৩ অক্ষর হতে হবে।",
        "reg_pass_short": "পাসওয়ার্ড কমপক্ষে ৬ অক্ষর হতে হবে।",
        "reg_pass_mismatch": "পাসওয়ার্ড দুটো মিলছে না!",
        "login_success": "লগইন সফল! স্বাগতম",
        "login_error": "ভুল ব্যবহারকারীর নাম বা পাসওয়ার্ড!",
        "language": "ভাষা",
        "district": "জেলা ও আবহাওয়া", "select_district": "জেলা নির্বাচন করুন",
        "get_weather": "আবহাওয়া আনুন", "fetching": "আবহাওয়া আনা হচ্ছে...",
        "weather_ok": "সফল", "weather_err": "ত্রুটি",
        "crop_field": "ফসল ও জমি", "crop_name": "ফসলের নাম",
        "soil_type": "মাটির ধরন", "season": "মৌসুম",
        "irrigation": "সেচ পদ্ধতি", "field_area": "জমির আয়তন (হেক্টর)",
        "weather_section": "আবহাওয়া", "auto": "(স্বয়ংক্রিয়)",
        "temperature": "তাপমাত্রা (ডিগ্রি সে.)", "rainfall": "বার্ষিক বৃষ্টিপাত (মি.মি.)",
        "humidity": "আর্দ্রতা (%)", "sunshine": "সূর্যালোক (ঘণ্টা/দিন)",
        "soil_inputs": "সার ও মাটি", "soil_ph": "মাটির pH",
        "nitrogen": "নাইট্রোজেন/ইউরিয়া (কেজি/হে.)",
        "phosphorus": "ফসফরাস/টিএসপি (কেজি/হে.)",
        "potassium": "পটাশিয়াম/এমওপি (কেজি/হে.)",
        "pesticide": "কীটনাশক (কেজি/হে.)",
        "predict_btn": "ফলন পূর্বাভাস করুন",
        "current_weather": "বর্তমান আবহাওয়া", "live": "লাইভ", "cache": "ক্যাশ",
        "weather_info": "সাইডবার থেকে জেলা বেছে 'আবহাওয়া আনুন' চাপুন - তাপমাত্রা ও আর্দ্রতা স্বয়ংক্রিয়ভাবে সেট হবে!",
        "ton_ha": "টন / হেক্টর", "predicted": "পূর্বাভাসিত ফলন",
        "total_ton": "মোট টন", "for_ha": "{a} হেক্টরে",
        "uncertainty": "অনিশ্চয়তা", "ci": "৯৫% CI [{lo} - {hi}]",
        "vs_avg": "গড়ের তুলনায়", "avg": "গড়: {avg} t/ha",
        "great": "চমৎকার! গড়ের চেয়ে {dl:.1f}% বেশি ফলন আশা করা যাচ্ছে।",
        "good": "ভালো অবস্থা। {ct} এর গড় ফলনের কাছাকাছি পাবেন।",
        "warn": "সতর্কতা! ফলন গড়ের চেয়ে কম হওয়ার সম্ভাবনা। মাটির pH ও সার পুনর্বিবেচনা করুন।",
        "tab1": "বিশ্লেষণ", "tab2": "ফিচার প্রভাব", "tab3": "ডেটা",
        "tab4": "মডেল রিপোর্ট", "tab5": "আমার ইতিহাস",
        "dist_chart": "ফলন বিতরণ", "your": "আপনার",
        "field_profile": "জমির প্রোফাইল", "season_chart": "মৌসুম অনুযায়ী গড় ফলন",
        "top10": "শীর্ষ ১০ ফসল", "avg_yield": "গড় ফলন (টন/হেক্টর)",
        "feature_title": "কোন বিষয় সবচেয়ে বেশি প্রভাব ফেলে?",
        "feature_rank": "ফিচার গুরুত্ব র্যাংকিং",
        "sensitivity": "সংবেদনশীলতা বিশ্লেষণ",
        "select_feature": "বিষয় নির্বাচন করুন:",
        "current": "বর্তমান", "yield_vs": "ফলন বনাম",
        "data_title": "ডেটা এক্সপ্লোরার", "total_records": "মোট রেকর্ড",
        "crop_types": "ফসলের ধরন", "avg_yield_lbl": "গড় ফলন",
        "x_axis": "X অক্ষ:", "raw_data": "কাঁচা ডেটা দেখুন",
        "model_title": "মডেলের কর্মক্ষমতা রিপোর্ট",
        "test_r2": "টেস্ট R2", "test_mae": "টেস্ট MAE", "test_rmse": "টেস্ট RMSE",
        "cv_r2": "CV R2",
        "no_overfit": "Overfitting নেই! Train-Test R2 gap = {gap:.4f} (আদর্শ < 0.05)",
        "slight_overfit": "সামান্য Overfitting। Gap = {gap:.4f}",
        "overfit": "Overfitting আছে। Gap = {gap:.4f}",
        "improvements": "প্রয়োগকৃত উন্নতিসমূহ",
        "train_vs_test": "Train বনাম Test তুলনা",
        "actual_vs_pred": "প্রকৃত বনাম পূর্বাভাস (Test Set)",
        "predictions": "পূর্বাভাস", "perfect_fit": "আদর্শ রেখা",
        "footer": "CropSense AI - বাংলাদেশ কৃষি - Streamlit + Scikit-learn + OpenWeatherMap",
        "logged_in_as": "লগইন করেছেন",
        "history_title": "আমার পূর্বাভাসের ইতিহাস",
        "no_history": "এখনো কোনো পূর্বাভাস সংরক্ষিত হয়নি।",
        "hist_crop": "ফসল", "hist_district": "জেলা",
        "hist_yield": "ফলন (t/ha)", "hist_total": "মোট (t)",
        "hist_area": "আয়তন (ha)", "hist_date": "তারিখ",
    }
}
